org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.243
loader_version_range=[1,)

## Mod Properties
mod_id=dragonsdelight
mod_name=Dragons Delight
mod_license=MIT
mod_version=1.0.0
mod_group_id=dragonsdelightteam.by.dragonsdelight

## Proxy
#systemProp.http.proxyHost=localhost
#systemProp.http.proxyPort=7897
#systemProp.https.proxyHost=localhost
#systemProp.https.proxyPort=7897

## Dependencies
delight_version=8083481
delight_version_range=[1.2.5,)

dragonsurvival_version=8871661
dragonsurvival_version_range=[2.0.0,)